import { createBrowserRouter, RouterProvider } from "react-router-dom"; // ✅ Correct import
import { Link } from "react-router-dom"; // ✅ Add Link for navigation

import React from "react";
import "../styles/NewMM.css";
import TopNav from "../components/TopNav";
import Footer from "../components/Footer";

function NewMM() {
  return (
    <div className="newmm-container">
      <TopNav />

      <main className="newmm-content">
        <h2>Just a Few Quick Steps First...</h2>
        <textarea
          placeholder="Insert your session notes below:"
          className="session-notes"
        ></textarea>
        <button className="generate-button">Generate!</button>
        <p className="api-output-placeholder">
          *MindMap generated by ChatGPT API goes here*
        </p>
      </main>

      <Footer />
    </div>
  );
}

export default NewMM;
